### ISSUE TITLE
argument errrors in intersect description for findOverlaps function results

### ISSUE THREAD

**Issue by alcor2019** [kasperdanielhansen/genbioconductor#3]
Hi,

In lines 195-196 of the IRanges_Basic.Rmd file, I think there are some errors for the arguments in the intersect function relatively to the description (line 192) :

`intersect(ir1[subjectHits(ov)[1]],
          ir2[queryHits(ov)[2]])`

has to be replaced by

`intersect(ir1[queryHits(ov)[1]],
          ir2[subjectHits(ov)[1]])`

Alain

**Comment by kasperdanielhansen** [comment]
Correct.
